require:
  - rubocop-performance
  - rubocop

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Enabled: false